### ISSUE TITLE
Copying of documents

### ISSUE THREAD

**Issue by xet7** [sandstormports/sharelatex#4]
_From @zeigerpuppy on March 25, 2016 1:14_

This may be a more general sandstorm issue but I was wondering if it's possible to copy a document (grain). 
My usage of sharelatex has previously involve having a number of "template" docs which I copy and edit for use.  I imagine, many people would use the same workflow

_Copied from original issue: dwrensha/sharelatex#6_

**Comment by ocdtrekkie** [comment]
Sandstorm as a "clone grain" button now!

**Comment by zeigerpuppy** [comment]
fantastic, thanks!
Great to see the renewed activity lately.
